export const Scenes = {
    GREETER: '@scene-greeter',
    WEEKS: '@scene-weeks',
    WEEK1: '@scene-week1',
    WEEK2: '@scene-week2',
    WEEK3: '@scene-week3',
    WEEK4: '@scene-week4',
    TRAINING1: '@scene-training1',
    TRAINING1_EASY: '@scene-training1-easy',
    TRAINING1_MEDIUM: '@scene-training1-medium',
    TRAINING1_HARD: '@scene-training1-hard',
    TRAINING1_EASY_1: '@scene-training1-easy-1',
    TRAINING1_EASY_2: '@scene-training1-easy-2',
    TRAINING1_EASY_3: '@scene-training1-easy-3',
    TRAINING1_MEDIUM_1: '@scene-training1-medium-1',
    TRAINING1_MEDIUM_2: '@scene-training1-medium-2',
    TRAINING1_MEDIUM_3: '@scene-training1-medium-3',
    TRAINING1_HARD_1: '@scene-training1-hard-1',
    TRAINING1_HARD_2: '@scene-training1-hard-2',
    TRAINING1_HARD_3: '@scene-training1-hard-3',
    TRAINING2: '@scene-training2',
    TRAINING2_EASY: '@scene-training2-easy',
    TRAINING2_MEDIUM: '@scene-training2-medium',
    TRAINING2_HARD: '@scene-training2-hard',
    TRAINING3: '@scene-training3',
    TRAINING3_1: '@scene-training3-1',
    TRAINING3_2: '@scene-training3-2',
    TRAINING3_3: '@scene-training3-3',
    TRAINING4: '@scene-training4',
    TRAINING4_EASY: '@scene-training4-easy',
    TRAINING4_MEDIUM: '@scene-training4-medium',
    TRAINING4_HARD: '@scene-training4-hard',
    TRAINING5: '@scene-training5',
    TRAINING6: '@scene-training6',
    TRAINING6_HARD: '@scene-training6-hard',
    TRAINING6_EASY: '@scene-training6-easy',
    TRAINING6_MEDIUM: '@scene-training6-medium',
    TRAINING7: '@scene-training7',
    TRAINING7_EASY: '@scene-training7-easy',
    TRAINING7_HARD: '@scene-training7-hard',
    TRAINING7_MEDIUM: '@scene-training7-medium',
    TRAINING8: '@scene-training8',
    TRAINING8_EASY: '@scene-training8-easy',
    TRAINING8_HARD: '@scene-training8-hard',
    TRAINING8_MEDIUM: '@scene-training8-medium',
    TRAINING9: '@scene-training9',
    TRAINING9_EASY: '@scene-training9-easy',
    TRAINING9_HARD: '@scene-training9-hard',
    TRAINING9_MEDIUM: '@scene-training9-medium',
    TRAINING10: '@scene-training10',
	TRAINING10_EASY: '@scene-training10-easy',
    TRAINING10_HARD: '@scene-training10-hard',
    TRAINING10_MEDIUM: '@scene-training10-medium',
    TRAINING11: '@scene-training11',
    TRAINING12: '@scene-training12',
    TRAINING13: '@scene-training13',
    TRAINING14: '@scene-training14',
    TRAINING15: '@scene-training15',
};

export const Commands = {
    RESULTS: 'results',
};

export const Mode = {
    DEV: 'DEV',
    PROD: 'PROD',
};
